import type { Metadata } from "next";
import "@/assets/styles/index.scss";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Taksu Technical Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="basicTheme">
      <body>
        <main className="text-white max-w-[425px] mx-auto min-h-screen">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
